"""Reusable GUI component contracts inside the provisional framework boundary."""

from .layout import (
    AUTO,
    FILL,
    NATURAL,
    STRETCH,
    ControlLayout,
    ControlLayoutDefaults,
    ControlLayoutTheme,
    CrossAxisMode,
    DimensionMode,
    ResolvedControlLayout,
    cross_axis_mode,
    resolve_control_layout,
)
from .attachments import Tooltip
from .events import ComponentEvent, ComponentEventType, action_callback
from .profile import (
    ComponentLayoutProfile,
    FRAMEWORK_COMPONENT_PROFILE,
)
from .controls import (
    Button,
    CheckBox,
    ComboBox,
    Label,
    NumericKind,
    NumericStepper,
    ProgressBar,
    Separator,
    Spacer,
    TextInput,
)
from .containers import (
    ControlColumn,
    ControlGrid,
    ControlRow,
    Dialog,
    PlacedComponent,
    PositionedPanel,
    SectionPanel,
)
from .placement import (
    AnchoredChild,
    AnchoredPlacement,
    AxisAnchor,
    Insets,
    Placement,
    PositionedChild,
    ResolvedPlacement,
    SizeConstraints,
    anchored,
    anchored_overlay,
    insets,
    overlay,
    placement_from_descriptor,
    positioned,
)
from .regions import (
    SplitOrientation,
    SplitPane,
    SplitPanel,
    TabContainer,
    TabPage,
)
from .fields import (
    DurationEditor,
    LabeledComboField,
    LabeledField,
    LabeledNumericField,
    NumericUnitField,
)
from .state import ComponentGroup
from .bindings import BindingSet, ValueBinding
from .renderer import (
    ComponentRenderer,
    clear_default_renderer,
    get_default_renderer,
    set_default_renderer,
)

__all__ = [
    "AUTO",
    "FILL",
    "NATURAL",
    "STRETCH",
    "AnchoredChild",
    "AnchoredPlacement",
    "AxisAnchor",
    "Insets",
    "FRAMEWORK_COMPONENT_PROFILE",
    "BindingSet",
    "Button",
    "CheckBox",
    "ComboBox",
    "ComponentEvent",
    "ComponentEventType",
    "ComponentGroup",
    "ComponentLayoutProfile",
    "ComponentRenderer",
    "ControlColumn",
    "ControlGrid",
    "ControlLayout",
    "ControlLayoutDefaults",
    "ControlLayoutTheme",
    "ControlRow",
    "CrossAxisMode",
    "Dialog",
    "DimensionMode",
    "DurationEditor",
    "Label",
    "LabeledComboField",
    "LabeledField",
    "LabeledNumericField",
    "NumericKind",
    "NumericStepper",
    "ProgressBar",
    "NumericUnitField",
    "Placement",
    "PlacedComponent",
    "PositionedChild",
    "PositionedPanel",
    "ResolvedControlLayout",
    "ResolvedPlacement",
    "SectionPanel",
    "SizeConstraints",
    "Separator",
    "Spacer",
    "TabPage",
    "TabContainer",
    "SplitPanel",
    "SplitPane",
    "SplitOrientation",
    "TextInput",
    "Tooltip",
    "ValueBinding",
    "action_callback",
    "anchored",
    "anchored_overlay",
    "clear_default_renderer",
    "get_default_renderer",
    "insets",
    "overlay",
    "placement_from_descriptor",
    "positioned",
    "cross_axis_mode",
    "resolve_control_layout",
    "set_default_renderer",
]
