"""Reusable semantic documentation subsystem for Dear PyGui applications."""

from .model import (
    DocBlock,
    DocCallout,
    DocCalloutKind,
    DocCodeBlock,
    DocIconKind,
    DocIconLine,
    DocLink,
    DocLinks,
    DocMedia,
    DocMediaKind,
    DocPage,
    DocParagraph,
    DocRole,
    DocSection,
)
from .renderer import DocumentationRenderer
from .typography import (
    DEFAULT_DOCUMENTATION_SCALE,
    DOCUMENTATION_SCALE_LABELS,
    DOCUMENTATION_SCALES,
    DocumentationTheme,
    documentation_scale_from_label,
    documentation_scale_label,
    normalise_documentation_scale,
    role_font_size,
)

__all__ = [
    "DocBlock",
    "DocCallout",
    "DocCalloutKind",
    "DocCodeBlock",
    "DocIconKind",
    "DocIconLine",
    "DocLink",
    "DocLinks",
    "DocMedia",
    "DocMediaKind",
    "DocPage",
    "DocParagraph",
    "DocRole",
    "DocSection",
    "DocumentationRenderer",
    "DocumentationTheme",
    "DEFAULT_DOCUMENTATION_SCALE",
    "DOCUMENTATION_SCALE_LABELS",
    "DOCUMENTATION_SCALES",
    "documentation_scale_from_label",
    "documentation_scale_label",
    "normalise_documentation_scale",
    "role_font_size",
]
